version: '3.8'

services:
  gbcms:
    build:
      context: .
      dockerfile: Dockerfile
    image: gbcms:latest
    container_name: gbcms
    volumes:
      - ./data:/data
      - ./test_data:/test_data:ro
    working_dir: /data
    command: --help
